spring:
  application:
    name: ms-benchmark
  redis:
    database: 0
    host: localhost
    port: 6379


server:
  port: 8900

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
